### ISSUE TITLE
WPF Renaming producing broken modules when protecting more than one exe at once

### ISSUE THREAD

**Issue by ElektroKill** [mkaring/ConfuserEx#105]
When I protect these modules using ConfuserEx(2.0 branch). One always ends not working. I suspect its due to the renaming of paths.

In one of the modules the paths do not match and the module doesn't start:
![image](https://user-images.githubusercontent.com/37494960/68069716-73086e00-fd64-11e9-9257-a1876bc22bb7.png)

In the second module, the paths match and it starts:
![image](https://user-images.githubusercontent.com/37494960/68069736-b19e2880-fd64-11e9-9d95-8eb2e119709a.png)

The next interesting thing is that both of the modules have the same path in the entry point: `ourbopoogrdveenjzkwpafdlxojra.xaml`

Here are the applications I am using:
[Apps.zip](https://github.com/mkaring/ConfuserEx/files/3800360/Apps.zip)

**Comment by ElektroKill** [comment]
Any update on this issue ? I know this isn’t a really big deal as not many people obfuscate more than one exe at a time.

**Comment by mkaring** [comment]
I identified the issue. It has actually nothing to do with the assemblies being executables. The problem causing this issue is that the two XAML files in both assemblies have the same name. The renamer does not distinguish the references by assembly. If two XAML files in different assemblies have the same name, the resources itself get different name, but the references get the name of what ever is renamed last.

This is likely to be a massive issue in larger WPF projects.

**Comment by mkaring** [comment]
I think I fixed the issue.
Could you please verify that the issue is gone using this build:
https://ci.appveyor.com/project/mkaring/confuserex/builds/29072060/artifacts

**Comment by ElektroKill** [comment]
Everything is working as expected. Thanks.

**Comment by mkaring** [comment]
Very good. It's merged in both `master` and the `release/2.0` branch now.
