### ISSUE TITLE
Constants protection triggers SecureAge APEX on VirusTotal

### ISSUE THREAD

**Issue by griknok** [mkaring/ConfuserEx#113]
I have tried every combination of settings using the 'contants' feature of ConfuserEx but I can't find any that don't trigger false positive with this engine, and so my site gets blacklisted by McAfee.
Is there a certain bit of code that's always included when using this protection that could instead be randomised in a way that it only sometimes triggers a false positive?

If not, could everyone file a report about SecureAge APEX being a really crappy engine that VirusTotal should stop using because its getting all our (obfuscation hosting) sites blacklisted by McAfee site protection? :D    I have already asked that they stop using it until it's better, maybe with enough complaints they will listen...

**Comment by griknok** [comment]
From experimentation with different settings and uploading to VirusTotal, using multiple builds of a very simple C# winforms app:

Invalid Metadata => Cyclance reports Unsafe, VBA32 reports CIL.HeapOverride.Heur
Control Flow (any setting) => SecureAge APEX reports Malicious
Constants (any setting) => SecureAge APEX reports Malicious, Ikarus reports Trojan.MSIL.Crypt
Ref Proxy (mode: Strong) => 9 engines report malware
Ref Proxy (mode: undefined, encoding: Normal, internal: true, typeErasure: true) => all good
Ref Proxy (Expression, true, true) => all good
Ref Proxy (x86, true, true) => all good
Resources => SecureAge APEX reports Malicious
Anti tamper (Normal or JIT) => Many, many things (9 or 16 engines!) report malware
Anti Debug (Safe) by itself => always fine
Anti Debug (Win32) => Cyclance reports Unsafe
Anti Dump by itself => always fine
Anti Il Dasm by itself => always fine
Anti Dump and Anti Debug together (regardless of Anti Il Dasm present or not) => Sangfor Engine Zero reports Malware

So this means currently I am only using:
Rename
Ref Proxy (Expression, true, true)
Anti Debug (Safe)
And everything else is currently un-usable because of stupid SecureAge APEX

**Comment by mkaring** [comment]
The problem is that ConfuserEx was and is used to obfuscate malicious applications from time to time. The more effective protections are (meaning the harder to read the result is), the more "suspicious" things need to be done.

For example the strong ref proxy mode, basically writes a byte array during runtime and than creates a method and instructs it to execute the byte array as the code of the method. That looks fishy for an anti virus application.

Some of the reports, like the combination of `Anti Dump` and `Anti Debug` are likely caused because that combination of code was seen in a couple of applications that were actually reported to be malicious.

There are only a few things that can be done here:
1. Sign your application, using the [SignTool.exe][0]. I found that the virus scanners are a bit more lenient in case the applications are signed.
2. Report the false positives. If your application is detected but is not a malicious application, report it to the providers of the anti virus solutions:
   * SecureAge APEX: [Report False Positive Detections][1]
   * Cyclance: [VirusTotal Inquiries][2]
   * Ikarus: [False Positives E-Mail contact][3]
  
   I am aware that this is a very tedious process, but in the end reporting the false positives is the only thing that helps long-term.

[0]: https://docs.microsoft.com/dotnet/framework/tools/signtool-exe
[1]: https://www.secureaplus.com/features/antivirus/report-false-positive/
[2]: https://support.cylance.com/s/article/Cylance-VirusTotal?language=en_US
[3]: mailto:false-positive@ikarus.at

**Comment by griknok** [comment]
Yes I'll be sure to report lots of files to them :)
Thanks for all your efforts!
