### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by MulleDK19** [mkaring/ConfuserEx#17]
I've got issues with the current 1.0 release of ConfuserEx, not renaming references in XAML, so all WPF applications break, unless I don't rename classes, which kinda defeats the purpose.

Could you make a release of this fork? I really don't wanna deal with .NET Core.

**Comment by mkaring** [comment]
I can easily release a 1.1 version of ConfuserEx, but you can just as easy try the snapshot build of the 1.1 version at AppVeyor.

Simply download it from here:
https://ci.appveyor.com/project/mkaring/confuserex/branch/master/artifacts

If that version is not working for you properly, I'll need some more details what breaks for you. The version should properly handle renaming XAML files.

**Comment by MulleDK19** [comment]
Thanks, but that didn't change much.

I don't know if I should add this as a separate issue.

It's not renaming XAML files that's a problem, it's references to properties. It correctly renames XAMLs and references to the XAML class, but properties remain untouched. If I set `renPublic` to true, it renames them all, but doesn't update references in XAML, breaking the application.

Being able to read property names makes it easy to figure out what a class is for.

I'm starting to think renaming XAML referenced properties is just not supported?
I did some tests, and it does not rename properties if the class implements `INotifyPropertyChanged` **or** the property name is present in XAML. That is, if `Bla` is present in XAML, all properties named `Bla` in any class, whether the class is ever used or not, will not get renamed.

The latter is probably because bindings don't specify a specific class, so you can't know which property the binding is actually referring to.

However, surely it would be possible to detect property names used in XAML (which it already does), and then rename those properties to identical names. Then it doesn't have to know which which class it's in. So if a class has a property named `Bla` and `Bla` is referenced in any XAML, it obfuscates the property name to eg. `dK93aK19`, and then remembers that name to rename all other properties called `Bla` also to `dk93aK19`.

Shouldn't be too hard to walk the bodies of methods to detect strings with property names, so that classes that implement `INotifyPropertyChanged` can be obfuscated.

I mean, the only problem would if a string is "Hello" and there's a property somewhere named "Hello"; that string of course shouldn't be changed. But it wouldn't be too hard to only rename strings that are used in calls to a `RaisePropertyChangedEvent()` method.

**Comment by mkaring** [comment]
Renaming properties that are referenced from XAML is disabled by default. I am not sure why it renames the properties if you set `renPublic`. It shouldn't do that. The problem with references from XAML is that it is very difficult to properly rename it, because there are many methods to report changes (`DependencyProperty`, `INotifyPropertyChanged`) and it is currently not supported to rename this.
The default behaviour is that every property with a matching name that is referenced from XAML is not renamed. That is unless the property is referenced with a explicit type. The real problem with renaming the non-explicitly set properties is that I can't even say that the property is in the same assembly.

Renaming the properties (along with their update mechanism) is something I have planned for the future, but currently it just can't do it. That is for references that are set with an explicit type. For references without explicit type, that will not work, because the proper target property can't be identified.
