### ISSUE TITLE
ERROR running ConfuserEx

### ISSUE THREAD

**Issue by Palollo** [mkaring/ConfuserEx#18]
The target framework of application to protect is .NET 2.0.
Following exception is thrown:
[ERROR] Failed to resolve a member, check if all dependencies are present in the correct version.
Exception: dnlib.DotNet.MemberRefResolveException: Could not resolve method: System.Boolean System.Reflection.MethodInfo::op_Inequality(System.Reflection.MethodInfo,System.Reflection.MethodInfo) (mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   in dnlib.DotNet.MemberRef.ResolveMethodThrow()
   in Confuser.Core.DnlibUtils.ResolveThrow(IMethod method)
   in Confuser.Protections.ReferenceProxy.MildMode.ProcessCall(RPContext ctx, Int32 instrIndex)
   in Confuser.Protections.ReferenceProxy.ReferenceProxyPhase.ProcessMethod(RPContext ctx)
   in Confuser.Protections.ReferenceProxy.ReferenceProxyPhase.Execute(ConfuserContext context, ProtectionParameters parameters)
   in Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context)
   in Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context)
   in Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)
[ERROR] ---BEGIN DEBUG INFO---
[ERROR] Installed Framework Versions:
[ERROR]     v2.0.50727  2.0.50727.4927
[ERROR]     v3.0  3.0.30729.4926
[ERROR]     v3.5  3.5.30729.4926
[ERROR]     v4
[ERROR]     Client  4.7.03056
[ERROR]     Full  4.7.03056
[ERROR]     v4.0
[ERROR]     Client  4.0.0.0
[ERROR]     v4.5 461808
[ERROR]

**Comment by mkaring** [comment]
I can't reproduce the issue. Can you send me the project file you are using, so I can check it with the same configuration?

**Comment by Palollo** [comment]
Sure.
[myApp.zip](https://github.com/mkaring/ConfuserEx/files/2778580/myApp.zip)

**Comment by mkaring** [comment]
Okay, so there are multiple issues there.
The error is a side effect due to an incompatibility between the "anti debug" protection and the .NET 2.0 framework. I can fixed the error that stops ConfuserEx from processing the entire assembly and a new build can be found [here][1], but that will not create a working assembly as long as the "anti debug" protection is enabled.

That being said, there is a way to get it working anyway. The upcoming 2.0 release contains a massive rework of the entire runtime code generation of ConfuserEx and it will create valid "anti debug" protection code. You can find the download for the upcoming 2.0 version [here][2].

So the options are to either disable the "anti debug" protection, move to .NET 4.5 or to use ConfuserEx 2.0. Please let me know how it goes.

[1]: https://ci.appveyor.com/project/mkaring/confuserex/branch/master/artifacts
[2]: https://ci.appveyor.com/project/mkaring/confuserex/branch/release/2.0/artifacts

**Comment by Palollo** [comment]
Ok, I've just disabled the "anti debug" protection by now. I will change to .NET 4.6, soon. And I will test ConfuserEx 2.0 (the branch) (I didn't know it). Thanks a lot.

**Comment by mkaring** [comment]
Did you already have the chance to try protecting your assembly with the 2.x branch? I'm very interested in the result.
