### ISSUE TITLE
ConfuserEx and ConfuserEx 2

### ISSUE THREAD

**Issue by invisiblepatriot** [mkaring/ConfuserEx#197]
For one of our products we use ConfuserEx to obfuscate our dlls. I was wondering is it possible to check if ConfuserEx has failed to obuscate a dll using a .bat script? This is so to stop the build. We are using MSbuild 2015.

And what is the difference between ConfuserEx and Confuser Ex 2? Should we move over to ConfuserEx 2?

Also, could you please explain if our dlls are obfuscated, when we run the application do the dlls get deobfuscated somewhere? Just need a little clarification on that

Warm regards

**Comment by mkaring** [comment]
That depends a bit on what you are doing during the obfuscation. If you are using the ConfuserEx CLI, you can use the error code of the application. It returns 0 if all is fine and 1 in case it any error was encountered. If it returns 0, all assemblies got processed according to your confuser project file.

If you are directly using the MSBuild integration, the build is going to fail in case there is any problem.

ConfuserEx 2 is a pretty extensive update to the current ConfuserEx, that is no where near finished. I strongly advice against using it in a productive environment. Stick to the [latest version of ConfuserEx][1] that is listed in the releases (as of writing this it's 1.4.1). 

The last one is a difficult question. The answer is: kind of. There are some protections that are reverted in order to execute the assembly. This is always done in memory and if possible only partly. For example protected constants need to be put in memory at some point in time when they are used. They are decrypted one at a time upon request. The anti tamper protection for example restores the "real" assembly in memory before it's executed. Other protection don't revert the protection at all. For example renaming or the control flow obfuscation is never undone.

[1]: https://github.com/mkaring/ConfuserEx/releases/latest
