### ISSUE TITLE
could not obfuscate some libraries

### ISSUE THREAD

**Issue by ismlsmile** [mkaring/ConfuserEx#299]
I am testing obfuscate a library embeding several other library. As a result,  some classes and enums are not obfuscated, and there is a warning on Ionic.Zip

here is the log:
 [INFO] Confuser.Core 1.5.0-alpha+74b9dfa7f9 Copyright © 2014 Ki, 2018 Martin Karing
 [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 13 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'TestWinForm.exe'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
[DEBUG] Executing 'Type scanner' phase...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[DEBUG] Analyzing...
[DEBUG] WinForms found, enabling compatibility.
 [WARN] Could not find backing code for resource type 'Ionic.Zip.Forms.PasswordDialog', protections may not apply to that type.
 [WARN] Could not find backing code for resource type 'Ionic.Zip.WinFormsSelfExtractorStub', protections may not apply to that type.
 [WARN] Could not find backing code for resource type 'Ionic.Zip.Forms.ZipContentsDialog', protections may not apply to that type.
 [INFO] Processing module 'TestWinForm'...
[DEBUG] Executing 'Invalid metadata addition' phase...
[DEBUG] Executing 'Renaming' phase...
[DEBUG] Renaming...
[DEBUG] Executing 'Anti-debug injection' phase...
[DEBUG] Executing 'Anti-dump injection' phase...
[DEBUG] Executing 'Anti-ILDasm marking' phase...
[DEBUG] Executing 'Encoding reference proxies' phase...
[DEBUG] Executing 'Constant encryption helpers injection' phase...
[DEBUG] Executing 'Resource encryption helpers injection' phase...
[DEBUG] Executing 'Type scrambler' phase...
[DEBUG] Executing 'Constants encoding' phase...
[DEBUG] Executing 'Hardening Phase' phase...
[DEBUG] Executing 'Anti-tamper helpers injection' phase...
[DEBUG] Executing 'Control flow mangling' phase...
[DEBUG] Executing 'Post-renaming' phase...
[DEBUG] Executing 'Anti-tamper metadata preparation' phase...
[DEBUG] Executing 'Apply watermark' phase...
[DEBUG] Watermarking...
[DEBUG] Executing 'Packer info extraction' phase...
 [INFO] Writing module 'TestWinForm'...
[DEBUG] Encrypting resources...
 [INFO] Finalizing...
[DEBUG] Saving to 'xxx\TestWinForm.exe'...
[DEBUG] Executing 'Export symbol map' phase...
 [INFO] Done.
Finished at 13:31, 1:09 elapsed.

![image](https://user-images.githubusercontent.com/1876179/104685739-b6b38180-5736-11eb-828e-8a66acda81f4.png)

**Comment by mkaring** [comment]
The resource warning rarely is a problem. It just indicates that encrypting the resources did not work, because the way the resources are loaded was not detected perfectly. That means usually that some resources, containing texts and translations are not obfuscated. You can check if there is anything important in those resources, if there is nothing in there, you don't need to stress about those warnings.

Regarding the missing obfuscation of the enum types. That usually happens if ConfuserEx detects that the enum values may be referenced by name in the code. To avoid breaking anything there, the enums are skipped for the obfuscation.
You can force rename those enums, but this may have unintended side effects. Have a look at the rename protection in the wiki on details how to force the renaming.

**Comment by ismlsmile** [comment]
ok, thanks for your reply.
