### ISSUE TITLE
rename protection making app not start

### ISSUE THREAD

**Issue by yoyos** [mkaring/ConfuserEx#303]
HI,

I just did a quick test with a .NET Standard 2.1 lib with maximum protection

```
 [INFO] Confuser.Core 1.5.0-alpha Copyright © 2014 Ki, 2018 - 2021 Martin Karing
 [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 13 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'XXX.Lib.dll'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
[DEBUG] Executing 'Type scanner' phase...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[DEBUG] Analyzing...
 [INFO] Processing module 'XXX.Lib.dll'...
[DEBUG] Executing 'Invalid metadata addition' phase...
[DEBUG] Executing 'Renaming' phase...
[DEBUG] Renaming...
[DEBUG] Executing 'Anti-debug injection' phase...
[DEBUG] Executing 'Anti-dump injection' phase...
[DEBUG] Executing 'Anti-ILDasm marking' phase...
[DEBUG] Executing 'Encoding reference proxies' phase...
[DEBUG] Executing 'Constant encryption helpers injection' phase...
[DEBUG] Executing 'Resource encryption helpers injection' phase...
[DEBUG] Executing 'Type scrambler' phase...
[DEBUG] Executing 'Constants encoding' phase...
[DEBUG] Executing 'Hardening Phase' phase...
[DEBUG] Executing 'Anti-tamper helpers injection' phase...
[DEBUG] Executing 'Control flow mangling' phase...
[DEBUG] Executing 'Post-renaming' phase...
[DEBUG] Executing 'Anti-tamper metadata preparation' phase...
[DEBUG] Executing 'Apply watermark' phase...
[DEBUG] Watermarking...
[DEBUG] Executing 'Packer info extraction' phase...
 [INFO] Writing module 'XXX.Lib.dll'...
[DEBUG] Encrypting resources...
 [INFO] Finalizing...
[DEBUG] Saving to 'C:\<path>\XXX.Lib.dll'...
[DEBUG] Executing 'Export symbol map' phase...
 [INFO] Done.
Finished at 07:43, 0:00 elapsed.
```

Result is I can't start my wpf .net5 app using this lib. I don't have any error, it just doesn't start anymore.
Only by removing the rename protection, the app will work.
Have I made a mistake somewhere ? Should I do something else to make it work ?

![image](https://user-images.githubusercontent.com/1993859/104799402-21b09700-57cf-11eb-8b4a-359e80d42d14.png)

Thanks !

**Comment by mkaring** [comment]
This is too few information to tell you anything. WPF relies highly on reflection and a problem may be that the obfuscation changes the names of some properties and breaks the bindings in WPF this way.

A common way for this to happen, is if you implement a view model based on a interface and declare the view model class and/or the properties as `internal` or `private`. If you write the bindings directly accessing the property types instead of referencing the interface, this is likely causing the issue.

To get a clearer picture, I'd suggest to disable renaming for all classes that are directly referenced by the WPF bindings and see if that gets you somewhere.

Also it may be helpful to start the application with a debugger or in the command line to get the actual error that happens during startup.

**Comment by yoyos** [comment]
Thanks for info @mkaring  :)
I only put the rename protection and started the debugger after replacing my dll and got this:

`Each parameter in constructor 'Void .ctor(Double, Double)' on type XXX' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. The match can be case-insensitive.`

It appears I was putting some converters in wrong order after have changed from newtonsoft to text.json.
I don't know how it could work before using confuserEx :D

Its running smoothly now :) :)
Big thank u !

**Comment by yoyos** [comment]
@mkaring I tested again and I still have the error with rename.
I think it's coming from elsewhere and I didn't test correctly last time with an abfuscated dll.

This error could be coming from this braking change with .NET5 so maybe there is something in ConfuserEx that needs to be tweaked according to this breaking change ?

https://github.com/dotnet/runtime/issues/42973

**Comment by mkaring** [comment]
Okay. Disable the rename obfuscation for the type that is shown in the error message. The deserialization expects that there is a property or field matching the name of the constructor parameter. This is something ConfuserEx is not supporting yet out of the box.

You need to disable renaming for the type (or at least for the constructor and the parameters), so the deserialization works properly.

**Comment by yoyos** [comment]
Yes I tried to read the fixes but
- I don't use parameterless constructors at all 
- they are all public already
- tried the jsonconverterattribute too
- My converters are set for those types. 
 
So don't know what else I can do.

I'll check for excluding this type when I'll find the syntax

**Comment by mkaring** [comment]
The point of the issue is that you should use parameterless constructors. Those constructors with parameters cause the problem.
Even for public types and constructors, ConfuserEx will remove the names of the parameters. For the serialization to work, you need properties and parameters with matching names.

So to disable ConfuserEx for the specific type, just add a new rule with the pattern `full-name('Full.Name.Of.Your.Type')` and remove the renamer for this rule.

There are lots of options on how to select the types you need. Maybe another way suits your case better. You can find the documentation regarding the  expression functions [here](https://github.com/mkaring/ConfuserEx/wiki/Expression-Functions).

**Comment by yoyos** [comment]
How do you use basic ioc with parameterless constructors ? Injection is made by adding parameters to constructors right ?

**Comment by mkaring** [comment]
Constructors with parameters aren't a general problem. The problem is that the library you are using to serialize your classes for remoting or for saving them to files, doesn't like those too much.

**Comment by mkaring** [comment]
@yoyos: Did you get your issues sorted out?

**Comment by yoyos** [comment]
Sorry yes, I skipped types like you said :) thanks !
