### ISSUE TITLE
Reversed strings

### ISSUE THREAD

**Issue by maxplayle04** [mkaring/ConfuserEx#313]
Hello,
I'm having some trouble with ConfuserEx in that it will reverse all the strings I have in my binary whenever I confuse the binary with ConfuserEx. This doesn't happen when the binary isn't confused.

For a little context, it's an LSPDFR Callout Package - a modification for the game Grand Theft Auto V.

Is this something I'm doing wrong, as I know of many other people who use ConfuserEx for their LSPDFR Callout Packages who do not encounter this issue?

Any advice would be appreciated,

Many thanks,
Max

**See attached image for reference:**

![image](https://user-images.githubusercontent.com/63079841/106215782-9b7e5280-61c9-11eb-870c-896be19c639a.png)

**Comment by mkaring** [comment]
This isssue is usually caused by the Right-To-Left Override mark, that is part of all obfuscated type names when using the default unicode renaming mode.

Are you printing obfuscated type/member names into your text? They will not "show up", because most, if not all characters in the name are unprintable, but the RLO will still take effect.

**Comment by maxplayle04** [comment]
I'm just printing strings as if it was:
`Game.LogTrivial("Hello world!");`

And for some reason it'll come out as:

`!dlrow olleH`

Not sure why?

**Comment by maxplayle04** [comment]
That said in some logging functions, the name of the calling method is printed. Could that be why?

**Comment by mkaring** [comment]
That is very likely the reason. If the logging function fetches the caller name, this name may be broken, depending on how the name is retrieved.

**Comment by maxplayle04** [comment]
If it allows you to narrow down anything, the name is retrieved using the following code:

`var caller = new StackTrace().GetFrames(1).GetMethod().Name`

**Comment by maxplayle04** [comment]
Thank you for your comments so far however :)

**Comment by mkaring** [comment]
Yes. This is the cause of the problem. Because it prints the name of the calling method, the character of the obfuscation take effect.

There isn't much you can do about this:
* Find a way to disable printing the name of the calling method
* Disable the rename obfuscation for every method that calls the logging by adding `[Obfuscation(Exclude = False, Feature = "-rename")]`
* Limit the renamer for those methods, so you can at least read the output.
* Add the character `"\u202D"` in front of your logging texts 😁

**Comment by maxplayle04** [comment]
I shall use that last option and see if it helps! Thank you very much for your assistance. I'll close this issue for now although may reopen it if I find myself so stupid I can't figure anything out! *It's been a tough week! 😁😂*

Thanks very much :)

**Comment by maxplayle04** [comment]
Sorry to reopen this issue. Even with that character, I'm still having no luck. Is there any way to disable the name obfuscation for the entire assembly? Because everything is `internal`, I'm not so worried about method names being exposed as I'm using an API where people will be familiar with the override method names regardless.

**Comment by mkaring** [comment]
Okay, so I'm guessing your issue is that public types are obfuscated because your assembly is an executable? If that is the case, this can be easily fixed. You can disable it in the confuser project file, by adding the required parameter to the rename protection:

```
  <protection id="rename">
    <argument name="renPublic" value="false" />
  </protection>
```

This will stop ConfuserEx obfuscating anything that is `public`.

You'll find more information about the options you got in the [wiki](https://github.com/mkaring/ConfuserEx/wiki/Name-Protection).

**Comment by maxplayle04** [comment]
I'll have a look into this. Thank you.
