### ISSUE TITLE
Type renaming gets conflicted after #305

### ISSUE THREAD

**Issue by wmjordan** [mkaring/ConfuserEx#375]
Repost from #305 :

I downloaded the artifact and used it to process my assembly without the `shortNames` option.
I ran the output and the runtime reported a `System.BadImageFormatException` that there was a duplicated type `JqLoWOMO_NHYI5jO_oKtDdg`.

I inspected the assembly and found up to four of them:
![image](https://user-images.githubusercontent.com/12182730/125708960-e1b58572-8c7e-4c11-8792-b5a0fd4b4eee.png)

I decoded the name and found that it was not prefixed with the namespace. Yet other types were prefixed with their namespaces if their names were decoded.

Originally, those four types were of the same name, but from various namespaces.

**If a type is referenced in an `Attribute`, things will go wrong.**

Please use the attached configuration and assembly.

[sample.zip](https://github.com/mkaring/ConfuserEx/files/6819648/sample.zip)

**Comment by wmjordan** [comment]
@KvanTTT let's continue here.

**Comment by KvanTTT** [comment]
Ok, I'll try to take a look at your sample this weekend.

**Comment by KvanTTT** [comment]
Could you please provide plain source code? I'm going to add it to tests data.

**Comment by KvanTTT** [comment]
Seems like I've found the error. I'll fix it ASAP.

**Comment by KvanTTT** [comment]
Please try this build: https://ci.appveyor.com/project/mkaring/confuserex/builds/40011572/artifacts

**Comment by wmjordan** [comment]
This build was working well.
Nothing went wrong.
Except that the output was somewhat larger than the released version.

**Comment by KvanTTT** [comment]
This is because there are a lot of methods with the same name. See the test [MethodOverloading](https://github.com/mkaring/ConfuserEx/blob/master/Tests/MethodOverloading/Program.cs):

In the old renaming, the only one name is used for all methods `OverloadedMethod` 

```
_phF8iy7Y79cwt3EaAFmJzW2bGch	OverloadedMethod
```

In the new renaming, there are different names:

```
_LzCBuBOSn49xbtKNsjuJxQZPIEW	MethodOverloading.Program::OverloadedMethod(System.Object[])
_iwS4d2WfWue8hAHbtgBSikKrN8w	MethodOverloading.Program::OverloadedMethod(System.Int32)
_tQShkhOLgB2RMcTPXJsvZDTAJOq	MethodOverloading.Program::OverloadedMethod(MethodOverloading.Program/NestedClass)
_kWJqUnE6117bEW5nvjyXejyFykF	MethodOverloading.Program::OverloadedMethod(T)
_ywSbkiShk8k3qj7bBrEWEUfs9Km	MethodOverloading.Program::OverloadedMethod(System.String)
_te2aE7Jn1PSWhbO9JVKaBuSh5eK	MethodOverloading.Program::OverloadedMethod(System.Boolean,System.Single,System.Double)
```

Also, I noticed that the `reversible` renaming mode created very long names: [MessageDeobfuscationWithPassword](https://github.com/mkaring/ConfuserEx/blob/master/Tests/MessageDeobfuscation.Test/MessageDeobfuscationTest.cs#L48-L52). @mkaring maybe it makes sense to decrease size?

Or you can try to use `sequential` or at least `decodable` renaming modes if the output size is significant for you.

**Comment by wmjordan** [comment]
Understood!
Thank you for the quick fix and thorough explanation.

**Comment by mkaring** [comment]
@KvanTTT: Decreasing the size will only be possible in a very limited manner, because the original name has to be encoded in the name.

**Comment by KvanTTT** [comment]
Also, in `reversible` mode the size of output identifiers linearly depends on the size of input identifiers. In `sequential` and `decodable` modes there is no such dependence.

**Comment by wmjordan** [comment]
@KvanTTT Thank you for the detail.
It is reasonable and obvious that the `reversible` mode outputs longer member names if the original names are longer.

I compile and protect the assembly quite frequently and either the `sequential` or `decodable` mode can result in a lot of *.map files after one and another compilations cumulatively. Those map files can not be removed, otherwise it will be impossible to decode the stack traces when the old versions around somehow fail.
Do you have any experience about how to deal with that situation?

**Comment by KvanTTT** [comment]
I don't have such an experience. I have ideas to decrease output size for `reversible` mode:

* Use base91 encoding instead of base64. But it provides a small decrease and may use not allowed chars. That's why I'm not sure about this encoding.
* A lot of names have the same namespace, thus's it can be compressed in some way. This option looks more promising and provides better compression.

**Comment by wmjordan** [comment]
Using base91 might not be viable, since it may use not allowed chars as you mentioned above, which can bring undesired trouble when decrypting the trace later.
