### ISSUE TITLE
Performance Issue with Obfuscated Dlls

### ISSUE THREAD

**Issue by NaveenBadal** [mkaring/ConfuserEx#376]
Hi

We have a project, in which we read and decode some files and put the data into database. Without obfuscation, the same file processes in almost 3 to 4 minutes. While with the obfuscated dlls, it is taking around 12 to 14 minutes.
 This is my confuserex configuration. I went through a link (https://github.com/yck1509/ConfuserEx/issues/360) of previous version of confuser ex, in which a user has same problem. In that it mentions, Constants and Control Flow is causing a performance impact. So I tried to remove the Control Flow and Constants protection and surprisingly the time drops dows to 4 to 5 minutes from 12 to 14 minutes. Please suggest us, how we can improve the performance. As removing these protection, doesn't seem to be a good idea. 

 Current Using the Stable Release Version -> 1.5.0

Configuration : 
```
<rule preset="maximum" pattern="true">
        <protection id="anti debug" action="remove" />
		<protection id="anti dump" />
		<protection id="anti ildasm" />
		<protection id="anti tamper" />
		<protection id="constants"/>
		<protection id="ctrl flow" />
		<protection id="invalid metadata" action="remove" />
		<protection id="ref proxy" action="remove" />
		<protection id="resources" />
		<protection id="rename" action="remove"/>
		<protection id="harden" />
		<protection id="watermark" action="remove" />
		<protection id="typescramble" action="remove" />
    </rule>
```

**Comment by mkaring** [comment]
There is some performance impact that is caused by both protections for sure. But your case seems excessive. The problem is likely caused by a function that is running very often or a function with a long running loop. Either is possible. Both protections introduce additional checks and calculations that just need some runtime as well. If you got a method that is run very frequently, the protections may have such an effect.

The easiest option that comes to mind would be to disable the protections _for the specific method(s)_ that are most performance critical, by the definitions mentioned above.

You could also try to use native decoder methods for the protections, if you do not require the assembly to be "Any CPU" capable. You can so so by switching the predicate/mode to "x86". You'll find some information about this in the wiki:

* [Constants](https://github.com/mkaring/ConfuserEx/wiki/Constants-Protection)
* [Control Flow](https://github.com/mkaring/ConfuserEx/wiki/Control-Flow-Protection)
