### ISSUE TITLE
Localization File. satellite assembly

### ISSUE THREAD

**Issue by BBUBBA** [mkaring/ConfuserEx#388]
- ConfuserEx Version: 1.5.0
- Target Framework: 4.0
- Operating System: Win 10 x64

Case 1.

I need portable application. 
when i use Fody + Resource.embedder. + Confuser
i can't make portable application.

if have satellite assembly Folder.
![image](https://user-images.githubusercontent.com/17864839/127423559-94f8a5bf-7386-402b-8dcd-da308c8c458a.png)

Good work.. But is not portable app T_T

I Hope how can i use Resource.embedder File??
![image](https://user-images.githubusercontent.com/17864839/127423652-9c7699b0-95c7-4065-8f0e-68a0fc8951a8.png)

can i skip rename just resource file?

i think if Skip rename  ".resource file" is good work..

Case 2.

and.. sometime... satellite file random rename.

![image](https://user-images.githubusercontent.com/17864839/127423951-3b8e6d84-c46c-45a1-9c61-791f261c907b.png)
ko-KR - Random rename.. ( somefile rename, somefile not rename...)

![image](https://user-images.githubusercontent.com/17864839/127424668-446fedf4-8a81-42d4-8ab4-b32fe40e48b2.png)

es - Full rename.. Good work. ( Check it "_JCj9UWqMdsm69QOxLGumrSAkBiI" )
ko - Full rename..Good work.

i will try search that... why?
when if i can make simple project tell you..

Confuserex really Good is Fantastic solution. Thank you !!!!!!!!

* sorry my english is not good..

**Comment by mkaring** [comment]
Using the Fody resource embedder together with ConfuserEx is not going to work, because the assemblies that are stored inside of the main assembly will not be processed.

To work around this issue you've got multiple possibilities:

1. You can disable the renaming for the affected types. The resources files are renamed together with the types used to access theses resources. Meaning if you exclude the types that are used to access the resources from renaming, the resource files will remain untouched. You can do so by adding a new rule to your project file and use the [Expression Functions](https://github.com/mkaring/ConfuserEx/wiki/Expression-Functions) to disable the `name` protection for the specific type. I suggest using `full-name` or `match-name` to select the types you need. Alternatively you can exclude the types in code using the [declarative obfuscation](https://github.com/mkaring/ConfuserEx/wiki/Declarative-Obfuscation)
2. Alternatively you drop the Fody thing and use the [compressor](https://github.com/mkaring/ConfuserEx/wiki/Compressor) to create a single assembly deployment.

**Comment by BBUBBA** [comment]
Thank you for reply to me !!!

But i don't use fody & resource embedder when Case 2.

you can check it here

https://github.com/mkaring/ConfuserEx/issues/389

TEST.Zip File...

![image](https://user-images.githubusercontent.com/17864839/127490977-bd02ef39-4199-44a9-be1e-3e2a3eb9eaa6.png)

i Think Case 2 
When CultureInfo name have "-" dash and multiple Language FIles, Case 2 is Fire.
(  ko-kr, us-en )

i saw ko_kr & en_us (under bar) when decompile after packing confuserex.

Thank you !!!!!!!!!!!!!!!!!!!!!!!
Have a nice day ^^

**Comment by BBUBBA** [comment]
Case 1 is Solve now !!!!!!!!!!!!

i try use compressor function after Remove Fody & Resource embedder.

satellite assembly (Language File) is perfect merge and good work ^^

but. case2 is.. not Finish...
Just "ko-kr" Bug...

**Comment by BBUBBA** [comment]
Good Morning....

Hello.. 

if i use compressor function...

virustotal tell me so many virus...

i don't want false positive..

so can i merge Language resource without compress???

**Comment by BBUBBA** [comment]
i solve that.. 

but not Beautiful.. T_T

[TEST.zip](https://github.com/mkaring/ConfuserEx/files/6905493/TEST.zip)

![image](https://user-images.githubusercontent.com/17864839/127610944-ba6abee4-41ca-4075-9062-b0c4606c1de6.png)

Thank you ^_^

**Comment by mkaring** [comment]
The only way ConfuserEx is able to merge multiple assemblies is using the compressor. There is no other option. The name of the resources for Windows Forms have to match the name of the type that is used for windows forms.

So if you add the following attribute to your windows forms you can disable the renaming for the specific type:
```c#
[Obfuscation(Exclude = false, Feature = "-rename")]
```

Alternatively you can add a new rule to your `crproj` file that disables the renaming for the specific types you need. Based of the example you send for #389 this rule needs to be added as second rule:
```xml
  <rule pattern="inherits('System.Windows.Forms.Form') and member-type('type')" inherit="false">
    <protection id="rename" action="remove" />
  </rule>
```
For resources not based on windows forms, you have to add similar additional rules.

**Comment by BBUBBA** [comment]
Good Work !!!!!!! Nice Job ^_^

![image](https://user-images.githubusercontent.com/17864839/127742749-0482c11f-c16d-4cc7-886e-c8be708e7c43.png)

Thank you !!!!!!!!!!!!!!!!
