### ISSUE TITLE
Error whith Costura.Fody

### ISSUE THREAD

**Issue by Mrgaton** [mkaring/ConfuserEx#396]
- ConfuserEx Version:
- Target Framework:
- Operating System:

Steps to Reproduce:

1. intall the package costura foody to an proyect
2. install another package like Newsoft.josn
3. try to obsfucate it and

![image](https://user-images.githubusercontent.com/68958481/128894123-2ffeb47b-0213-441a-8dfd-6c9ab8c6e066.png)

**Comment by Mrgaton** [comment]
@mkaring

**Comment by ElektroKill** [comment]
ConfuserEx needs all the dependencies to function properly. Costura.Fody embeds these dependencies into the module and ConfuserEx is unable to resolve them as it expects them to be present next to the file or in other locations such as GAC.

Solutions:
1. If your file is a executable you can remove Costura.Fody and instead of the `compressor` packer which has the option to embed dependency dlls. This is a superior option as the dependencies are also encrypted.
2. Disable cleanup in Costura.Fody and prevent it from deleting the dlls from the output folder (note: they will still be embedded.
	- Navigate and open FodyWeavers.xml in a text editor of your choice.
	- Modiy the contents to set the right costura option somewhat like this:
	```
	<Weavers>
  		<Costura DisableCleanup='true'/>
	</Weavers>
	```

**Comment by mkaring** [comment]
I'm too slow. Thanks @ElektroKill

**Comment by XenocodeRCE** [comment]
@mkaring

I got 2 ideas : 

- What if we extract all embedded dll files during the analysis phase ? 
- What if then we remove any Fody code and select `Compressor` packer automaticaly ? 

Would you accept a PR ?

**Comment by mkaring** [comment]
The workaround provided by @ElektroKill is the only thing that currently works. In that case the embedded assembly will still work, but is not subject to any protection.

The proper support for Costura will be part of the 2.0 release.
