### ISSUE TITLE
Using packer just throws exception at startup

### ISSUE THREAD

**Issue by uecasm** [mkaring/ConfuserEx#404]
- ConfuserEx Version:
   ```
   [INFO] Confuser.Core 1.5.0+b5197549e4 Copyright c 2014 Ki, 2018 - 2021 Martin Karing
   [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 64 bits
   ```
- Target Framework: 4.6.2

Steps to Reproduce:

```
[assembly: Obfuscation(Exclude = false, Feature = "packer:compressor")]
[assembly: Obfuscation(Exclude = false, Feature = "preset(minimum);-anti debug;")]
```

```
cd bin\Release
Confuser.CLI -n -o=%CD%\..\Confused %CD%\TestApp.exe
```

When I try running the resulting exe in the Confused directory, it just throws an exception immediately on startup:

```
System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  Source=mscorlib
  StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes() in f:\dd\ndp\clr\src\BCL\system\reflection\module.cs:line 1118
   at Main(String[] )
```

The `LoaderExceptions` property refers to all of the assemblies that were supposedly packed into the executable.

(Also, assuming this can be fixed, is there a way to exclude specific assemblies from being packed?)

**Comment by mkaring** [comment]
Is there any way you can send the test application you are using over? The packer would work fine and there are unit tests in place that verify that it is in fact working. So the issue is caused by something specific in your application.

You can exclude assemblies by not adding them to the confuser project. All assemblies that are being protected are packed into one assembly.
