### ISSUE TITLE
AntiDebug Module is not working.

### ISSUE THREAD

**Issue by acastillorobles77** [mkaring/ConfuserEx#410]
- ConfuserEx Version: 1.5.0+b5197549e4
- Target Framework: .NET Framework 4.5.1
- Operating System: Windows 11 Build 22000.176

Steps to Reproduce:

1. Add AntiDebug protection at Maximum level.
2. Protect the application.
3. Launch dnSpy and debug the protected application.
4. The application will run without any problem as if AntiDebug wasn't enabled.

**Comment by ElektroKill** [comment]
This is because dnSpy has a code to prevent detection of debuggers to aid reverse engineering. It is able to circumvent all the methods ConfuserEx uses in the "safe" antidebug mode. You can always try using the "win32" or the "antinet" mode which use more/more complex methods to prevent debugging. Both however can decrease compatibility with different runtimes and/or operating systems.

**Comment by acastillorobles77** [comment]
Oh, thank you.

**Comment by mkaring** [comment]
Are there any further information you need to know here, @acastillorobles77 ?

**Comment by acastillorobles77** [comment]
That's all, thanks for replying. If I found another bug I'll report it here.
