### ISSUE TITLE
System.ArgumentNullException at System.Linq.Enumerable.ToList after maximum obfuscation

### ISSUE THREAD

**Issue by bukkideme** [mkaring/ConfuserEx#472]
- ConfuserEx Version: Confuser.Core 1.6.0+447341964f
- Target Framework: .NET Framework 4.8
- Operating System: Win10 Home 21H2

Steps to Reproduce:

1. Create a Winform project with Linq in it
2. Build it
3. Use Confuser with maximum level

When I run my Winform app, I get the following error:

> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ZT:1<\&MNqBHXyn>AN|C!\&S60(.‫‮⁭‌‏‪‮‏⁮‌‏​⁭‍‍‎‭‪‏⁯⁫⁫⁯‪‍‎⁯‪‍‌⁭‏‌‏⁬‫‬‏‏⁮‮(Object , MessageReceivedEventArgs )

As a workaround and acceptable protection, I use for now only these options, and I do not get error anymore running my EXE:

![image](https://user-images.githubusercontent.com/51174971/161415197-1a7a1fd5-7c57-4d3a-8352-45450050135c.png)

**Comment by mkaring** [comment]
It's very difficult to know what is going on here without more details on your application. What happens in the event handler that is causing the issue for your?
Can you provide a minimal example to reproduce the issue?

**Comment by mkaring** [comment]
Obfuscating the names of the properties may interfere with the serialization of Newtonsoft Json, unless the names of the properties are specified using the `JsonProperty` attribute. So this may very well be a hint to the issue already.

**Comment by mkaring** [comment]
Okay, so the problem is that Newtonsoft.Json determines based on the names of the attributes, what property of the source json file needs to be put in what property. The issue is that ConfuserEx renames the properties, meaning the names don't match with the properties anymore, breaking the serialization.

Your Json in the example looks something like this:
```json
{
  "MyTime": "2022-04-06",
  "AxleMasses": []
}
```

Those property names have to line up with the names in the classes. ConfuserEx creates property names that aren't readable and not legal for property names in Json files. Even if Newtonsoft Json manages to create a file from this, it fails when deserializing the classes.

There are two ways to resolve that issue:

1.  Disable the name protection for all the fields  and properties of the classes used for serialization. If they are all in one namespace, you can do this for the entire namespace.
2.  Alternatively you can add the `JsonProperty` attribute to the properties. Newtonsoft Json will prefer using those to determine the name. In that case the code would need to be altered like this:
```c#
public class Data
{
  [DisplayName("Idő"), Browsable(true)]
  [JsonProperty(nameof(MyTime))]
  public DateTime MyTime { get; set; }

  [JsonProperty(nameof(AxleMasses))]
  public List<int> AxleMasses { get; set; }

  public Data()
  {
    AxleMasses = new List<int>();
  }
}
```

**Comment by bukkideme** [comment]
Thanks for the excellent explanation! Everything is clear :) Option number 1. is just fine for me, so I will go with it!
This is very easy to use, and now my test program works just fine :)

![image](https://user-images.githubusercontent.com/51174971/162058502-9aa928b0-d289-4f70-9696-715864a8c426.png)

**Comment by mkaring** [comment]
That is a working solution, how ever I would not recommend just disabling the the renaming completely. It's a strong protection as it irreversible alters your assembly.

If you for example have all your serialization classes in a namespace called `My.Serialization.Classes` you could a second rule with the pattern: `namespace('My.Serialization.Classes')` and remove the rename protection only for this namespace.
