### ISSUE TITLE
Various issues when building VB.Net project

### ISSUE THREAD

**Issue by i00** [mkaring/ConfuserEx#50]
The built file doesn't show at all and the output shows (Release 1.1.0):

> [WARN] Could not find resource type 'DBMLBuilderLib.Dbml'.
>  [WARN] Could not find resource type 'DBMLBuilderLib.Gen'.
>  [WARN] Could not find resource type 'DBMLBuilderLib.Utis'.
>  [WARN] Could not find resource type 'DBMLBuilderLib.Sql'.
>  [WARN] Failed to extract binding property name in 'System.Windows.Forms.Binding DBMLBuilder.AdvancedBindingExtensions::AddOrReplace(System.Windows.Forms.ControlBindingsCollection,System.String,System.Object,System.String,System.Boolean,System.Windows.Forms.DataSourceUpdateMode,System.Object,System.String,System.IFormatProvider)'.
>  [WARN] Failed to extract binding property name in 'System.Windows.Forms.Binding DBMLBuilder.AdvancedBindingExtensions::AddBindingLazy<TControl,TDataObject,TBindingControlDataType,TBindingDataType>(TControl,System.Linq.Expressions.Expression`1<System.Func`2<TControl,TBindingControlDataType>>,System.Object,TDataObject,System.Linq.Expressions.Expression`1<System.Func`2<TDataObject,TBindingDataType>>,System.Boolean,System.Windows.Forms.DataSourceUpdateMode,System.Object,System.String,System.IFormatProvider,System.Windows.Forms.ConvertEventHandler,System.Windows.Forms.ConvertEventHandler)'.
>  [WARN] Failed to extract binding property name in 'System.Void FastColoredTextBoxNS.HotkeysEditorForm::InitializeComponent()'.

**EDIT:** I think that the issue is with the constraints renaming ... it seems to work when I don't use that.

**Comment by mkaring** [comment]
Those warnings point to problems during the renaming, but they only mean that ConfuserEx did not rename some things because it was unable to resolve what the reference points to.

The first four messages mean that some resources where not renamed because the class accessing the resource was not found.

The fifth warning triggers because ConfuserEx can't resolve your custom function that adds the bindings. In case the property names are passed directly to the windows forms functions, ConfuserEx will automatically disable renaming for these properties. The warning means that this does not work and you have to disable renaming for the relevant properties yourself (if they are not public)

**Comment by mkaring** [comment]
There is a new build of the master branch that contains some improvements for the Windows Forms related issues. The build can be downloaded from [the buildserver][1].

Issue #54 is related.

[1]: https://ci.appveyor.com/project/mkaring/confuserex/branch/master/artifacts
