### ISSUE TITLE
Anti-virus detect my confused exe file as a threat

### ISSUE THREAD

**Issue by ju2pom** [mkaring/ConfuserEx#57]
I have BitDefender Antivirus Plus installed and it keeps moving my exe file into quarantine after ConfuserEx has obfuscated the file. Bitdefender suspect the presence of `Gen:Variant.Razy.496193` virus in the file.
Here are the rules I apply:
```xml
<protection id="anti debug" />
<protection id="anti dump" />
<protection id="anti ildasm" />
<protection id="constants" />
<protection id="ctrl flow" />
<protection id="invalid metadata" />
<protection id="ref proxy" />
<protection id="anti tamper" />
```
Did anyone had the same kind of issue, and any idea on how to avoid this?
By the way, thanks for providing such a great tool !

**Comment by mkaring** [comment]
The "Gen:" header means that the scanner detected a "generic signature". So something that may be a virus, but it's not sure what virus it is exactly.

The problem is that some evil persons use applications like ConfuserEx to hide their code and that is the reason why the runtime code of ConfuserEx sometimes triggers the heuristics based detection of the virus scanners.  

What you can do:
1. Send your falsely detected executable to BitDefender for analysis. You'll help this project by doing so, because they will improve their detection code to produce fewer false positives. You can do so [here][2].
2. Try to disable the `"anti tamper"`. Usually it's this protection that triggers the anti virus applications.
3. If you have to option to do so: Try to sign the assemblies using the [signtool.exe][1]. At times this helps, even if you are using a untrusted certificate (don't ask me why that is)

Also: If you are actually developing malware - Please don't use ConfuserEx. :wink:

[1]: https://docs.microsoft.com/dotnet/framework/tools/signtool-exe
[2]: https://www.bitdefender.com/submit/

**Comment by KraftSystems** [comment]
It's very common, actually.

Many malware authors use ConfuserEx to obfuscate their code, so antivirus detect the whole protection signature as dangerous.
For my personal experience, the anti tamper protection is the only protection that triggers the antivirus. Remove It and you should be fine.

Sometimes fine tuning the protections, like ref proxy, ctrl flow and constant protection fooled the antivirus and the anti tamper protection could be kept active.

**Comment by Plicz** [comment]
Anti tamper is essential to protect, he said that added some debuggers checkup and that's good but confuserex easy to remove, if you want help with obfuscation tell me discord PliczCodeRCE#9243

**Comment by ju2pom** [comment]
Thanks for your answers, I'll first remove anti-tamper protection until my application is ready for shipping, then I'll consider submitting it to BitDefender.

And, no I'm not developing a malware :)
