### ISSUE TITLE
Any easy changes to ConfuserEx source code to break the famous de-obfuscation tools that target ConfuserEx?

### ISSUE THREAD

**Issue by glasgowrob** [mkaring/ConfuserEx#67]
I was able to get the source code of mkaring's ConfuserEx compiling so have started using this "compiled from source code" Confuser.CLI.exe to obfuscate by WPF/C# application.

Are there any easy changes that can be made to the ConfuserEx source code to break the famous de-obfuscation tools that target the standard (non-customized) version of ConfuserEx, other than those changes to the Constants protection described at [(https://github.com/yck1509/ConfuserEx/issues/26)] and [(https://github.com/yck1509/ConfuserEx/issues/444)]?

**Comment by mkaring** [comment]
Some of the obfuscations are by design relatively easy to reverse. There is just no way around it. Some of the tools utilize the watermark ConfuserEx places in the obfuscated assembly to identify it. So removing it may help here.

I already gave you a pretty detailed answer about the different protections in #64

There are some forks of ConfuserEx that do nothing but change constants names (like the "koi" that appears everywhere), remove the watermarking and change some constant values. But those only help against deobfuscators that specifically target ConfuserEx. More general deobfuscators (like de4dot) can do a lot of things without even knowing that the obfuscator is ConfuserEx. Against those only irreversible protections really help.

**Comment by glasgowrob** [comment]
Thanks, @mkaring. I really do appreciate your excellent advice in #64 . I have implemented much of your advice into my ConfuserEx obfuscation project file and it is working great.

Your answer above makes sense. So I guess that there really is no magic thing one can easily change in the ConfuserEx code to trick the best deobfuscators.

Like you recommended in previous replies and in your answer above, the most important protections are the irreversible ones, like the irreversible renaming, which works incredibly well! I will sleep well at night knowing that even if a competitor deobfuscates every thing but the ConfuserEx renaming, they will be in a world of hurt trying to make sense of any of it, unless they are so incredibly talented and patient that they can get any sort of mental model of what is going on. I am not even smart enough to figure out what is going on in my own code when renaming is fully applied, and I just wrote it!

I am closing this issue. Thanks again for everything, @mkaring!
