### ISSUE TITLE
Failed to extract binding property name

### ISSUE THREAD

**Issue by ustcltx** [mkaring/ConfuserEx#7]
Some warning messages appeared, what problems will it cause, can I ignore?
...
[DEBUG] WinForms found, enabling compatibility.
[DEBUG] Newtonsoft.Json found, enabling compatibility.
 **[WARN] Failed to extract binding property name in 'System.Void xxx.FrmTerminal::InitializeComponent()'.**
 [INFO] Processing module 'xxx.Base.dll'...
[DEBUG] Executing 'Invalid metadata addition' phase...
...

**Comment by mkaring** [comment]
This message appears in case you used a Windows Forms DataGrid with data binding. In those binding expressions point to a property in the bound object by a string.

Have a look at this [test file][1]. There you find the binding to the `BoundProperty` in the `DataBoundElement` class.

Now the error message means that ConfuserEx was unable to find and property with a matching name in the assembly. This means the target property is not automatically excluded from renaming. If the property is not renamed with your settings anyway (because it is in another assembly and `public` for example) it's not a problem and you can safely ignore that message.

If it is in the same assembly, it points to a problem with either your binding expression or ConfuserEx. If that is the case, it would be good if you can give me some additional information about the binding expressions you used and the object that contains the bound properties.

[1]: https://github.com/mkaring/ConfuserEx/blob/master/Tests/WinFormsRenaming/DataGridViewForm.cs

**Comment by mkaring** [comment]
Is this clearing up your problem?

**Comment by mkaring** [comment]
No more feedback. I can't analyze any issue without data. In case the issue is still present and you are able to provide more information, feel free to reopen the issue.
