### ISSUE TITLE
System.TypeLoadException after None-Obfuscation

### ISSUE THREAD

**Issue by soraphis** [mkaring/ConfuserEx#89]
I try to obfuscate *.dlls i use in a unity game

I'm using this ruleset: `<rule pattern="true" preset="none"></rule>`
(so I assume that nothing gets obfuscated, only an attribute added, which seems to be correct)

On some of the assembly I obfuscate with this rule set, the programm throws a System.TypeLoadException

like: 

```
System.TypeLoadException: Could not load list of method overrides due to assembly:....\Managed\mscorlib.dll type:IEnumerator`1 GameAdapter.DataInterface.IAccountCharacter {0}() signature:get_Current
```

its not always the mscorelib.dll (which is not obfuscated by the way). for some dlls they throw the same exception on other fields for the within the same dll.

But the files shouldn't be obfuscated at all, so I don't really understand why there are errors at all

**Comment by mkaring** [comment]
That is caused by the analysis phase of the renaming obfuscation. This part is executed, no matter if you enabled the renamer or not. A lot of issues in regards to this problem were fixed lately.

I suggest you give [this build][1] a try. It contains a few fixes that should help in your case.

[1]: https://ci.appveyor.com/project/mkaring/confuserex/branch/master/artifacts

**Comment by soraphis** [comment]
thanks a lot! will try on monday

**Comment by soraphis** [comment]
Worked like a charm! this build also enabled me to use more protection methods successfully.

sadly anti tamper doesn't work anymore (it worked before) now crashing on application start with an access violation exception in mono-2.0-bdwgc.dll.

but this issue can be closed. thanks!
