### ISSUE TITLE
How to Suppress Renaming a Type or a Member with the ObfuscationAttribute?

### ISSUE THREAD

**Issue by wmjordan** [mkaring/ConfuserEx#90]
I am sorry that I don't quite understand the usage of the ObfuscationAttribute with ConfuserEx. I tried quite a few times but not obtained reasonable results.

Could you provide an example? For instance, given the following code, how to prevent A and its members from being renamed with the ObfuscationAttribute? And how to prevent Y from being renamed (shall we apply the attribute on both A.Y and B.Y)?

``` C#
class A {
   public int X { get; set; }
   public virtual int Y { get; set; }
}
class B : A {
   public int Z { get; set; }
   public override int Y { get => Z; set => Z = value; }
}
```

**Comment by mkaring** [comment]
To stop the renamer from doing anything to `A` and it's members you can do this:
```C#
[Obfuscation(Exclude=False, Feature="-rename")]
class A {
   public int X { get; set; }
   public virtual int Y { get; set; }
}
```

As for the class `B`. The class name of `B` will be changed. But the member name of `Y` will remain the same, because it has to line up with the member name in `A`.

This relies on the [`ApplyToMembers` attribute of the `ObfuscationAttribute`][1] to be supported properly. There is a bug in ConfuserEx that was fixed in #75 and is part of the 1.3 builds. So you need a 1.3 version to get this working.

[1]: https://docs.microsoft.com/dotnet/api/system.reflection.obfuscationattribute.applytomembers?view=netframework-4.8

**Comment by wmjordan** [comment]
Thank you for your help.
It was working as expected.
It seems that I can drop my own fork of ConfuserEx and use yours :)

**Comment by mkaring** [comment]
I am always accepting pull requests, if you feel the need to change something :wink:
