### ISSUE TITLE
How to force renaming a type or member?

### ISSUE THREAD

**Issue by wmjordan** [mkaring/ConfuserEx#93]
I found that there were some types not renamed in the protected assembly, probably due to the detection of the `ldtoken` opcode.
I tried to apply the `[System.Reflection.Obfuscation(Exclude = false, Feature = "+rename")]` attribute on top of the type, but it was not working.

I am pretty sure that those types and its members could be renamed.
How to force them to be renamed?

**Comment by mkaring** [comment]
You can't force ConfuserEx to do that. If the analysis determines that the type can't be renamed, it won't be renamed, no matter what you do.
I'll enhance the trace-level logging to give some more information why something isn't renamed. Often times it's excluded because ConfuserEx sees the same type name in a reflection call or something like that and excludes it for that reason. Using it in `ldtoken` alone isn't a reason to exclude it. It depends on what is done with the token.

**Comment by wmjordan** [comment]
If we modify the [`DisableRename` method](https://github.com/mkaring/ConfuserEx/blob/release/2.0/Confuser.Renamer/Analyzers/LdtokenEnumAnalyzer.cs#L173), it is possible to force the rename prevented by the token analyzer.

If you don't want to do so, I will try to make a simple project demonstrating a type and its member which were not renamed.

**Comment by mkaring** [comment]
I'd rather not. The reason is that there is usually a reason why this method is called to disable the renaming. That reason is that the analyzer is not certain that a type can be renamed without breaking the application. I'd rather try to fix the specific case where a type can be renamed without issue, than allow a way to force renaming something.

**Comment by wmjordan** [comment]
Hmm, your concern makes sense.

I checked the code where the type and its members were not renamed and found the following pattern, which maybe the cause of the problem, and hard to "fix".

The code works like that:

```C#
foreach(var m in typeof(TheType).GetMethods()) {
    methodMapperDictionary.Add(m, typeBuilder.DefineField(m.Name, ....));
}
typeBuilder.CreateType();
```

After that, the code uses the `methodMapperDictionary` to do something, mapping the `MethodInfo`s to dynamically created fields. Actually the names of the dynamic fields were unimportant. They used the names of the methods just for debugging purpose.

ConfuserEx appeared to have detected the `ldtoken` and subsequent access to `Name` properties and decided to suppress the renaming. My case, which was absolutely rare, I think, should not be included into your consideration, but forceful renaming may be more appropriated.

**Comment by MathieuSteiner** [comment]
> forceful renaming may be more appropriated
We would love to have this come available (I'm currently facing such need)

**Comment by mkaring** [comment]
I understand that this may be handy something, but it really opens up a lot of potential issues. Let's take renaming methods for example. If the reflection finds a call to `GetMethod` or `GetMember` it will try to identify the type this is called for. This works fine if the original code was something like `typeOf(x).GetMethod(…)`, but if the source of the type was for example the parameter of the method, ConfuserEx is unable to identify the type.
Now it will simply not rename all methods with this name that are in the obfuscated assemblies. Now it's possible that one of the methods is marked for forced renaming. What to do in that case? Change the name in the call to `GetMethod` as well? Or leave it? Either way could be correct, but there is no way to be sure.

**Comment by wmjordan** [comment]
I understand your consideration.
In my case, leaving it won't break the application. In other cases, it is really problematic.

Is it possible to output an information with full names of those symbols, when ConfuserEx decides not renaming them, so we knows the unprotected spots and we can take some measures to work around it?

**Comment by MulleDK19** [comment]
I second this.

There are times where ConfuserEx just won't or can't make the proper decision.
For example, I have a lot of classes marked as serializable because they need to work with remoting, which leaves huge parts of the app completely unobfuscated, because ConfuserEx won't obfuscate types marked serializable.

**Comment by mkaring** [comment]
I did think about this while updating the wiki. It should already be possible to enforce the renaming for serialized types. I added an example for this exact case: https://github.com/mkaring/ConfuserEx/wiki/Name-Protection#example

Does this help?

**Comment by MulleDK19** [comment]
> I did think about this while updating the wiki. It should already be possible to enforce the renaming for serialized types. I added an example for this exact case: https://github.com/mkaring/ConfuserEx/wiki/Name-Protection#example
> 
> Does this help?

` Unknown token 'serializable' `

**Comment by mkaring** [comment]
Uh I have to fix the documentation... it should be:

```xml
<rule pattern="not is-public() and is-type('serializable')">
  <protection id="rename">
    <argument name="forceRen" value="true" />
  </protection>
</rule>
```
