### ISSUE TITLE
Problems with Reflection Type.GetMethods

### ISSUE THREAD

**Issue by GazziFX** [mkaring/ConfuserEx#94]
I use some reflection in my DLL which loads in Unity game (Uses Mono).
I get this Exception
https://pastebin.com/pdCy4g26

Code that stucks
https://pastebin.com/Qze4ZM6q

**Comment by mkaring** [comment]
What version of ConfuserEx are you using? Are there any warnings during the obfuscation?

**Comment by GazziFX** [comment]
Version 1.2.0
No warnings
Project settings: https://pastebin.com/9sFg9uRt
With same settings on vanilla ConfuserEx all works

**Comment by GazziFX** [comment]
With all protections disabled still have issue. Im really confused

**Comment by mkaring** [comment]
There are some known issues that may be linked to this issue that will be fixed in the next version. It would be really good if you could try it with the upcoming 1.3 release of ConfuserEx to see if the bug is still present.

You can download the latest preview version here: [ConfuserEx - AppVeyor Buildserver - Artifacts][1]

[1]: https://ci.appveyor.com/project/mkaring/confuserex/branch/master/artifacts

**Comment by GazziFX** [comment]
It works! Thanks a lot

**Comment by mkaring** [comment]
The 1.3 version is now properly released.
